# Generated by Django 3.1 on 2020-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franktestapp2020', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlydata',
            name='year_name',
            field=models.CharField(default=models.IntegerField(max_length=4), max_length=5),
        ),
    ]
