# Generated by Django 3.1 on 2020-08-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franktestapp2020', '0003_auto_20200824_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlydata',
            name='year_name',
            field=models.CharField(max_length=5),
        ),
    ]
