# Generated by Django 3.1 on 2020-08-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franktestapp2020', '0004_auto_20200824_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlydata',
            name='year_name',
        ),
    ]
