# Generated by Django 3.1 on 2020-08-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franktestapp2020', '0005_remove_yearlydata_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='pub_date',
        ),
    ]
